name: Deploy Site to gh-pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  deploy:
    name: Deploy Site to GitHub Page
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm install
      - name: Build site
        run: npm run build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
          clean: true
